import type { ExamConfig } from "@/lib/exams";

// This file is auto-generated by the employee portal.
// Do not edit manually unless you know what you are doing.

export const customTests: ExamConfig[] = [];
